WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entities;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

WebUI/Models/GamesListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Domain.Entities;

namespace WebUI.Models
{
    public class GamesListViewModel
    {
        public IEnumerable<GamesInOrder> Games { get; set; }
        public IEnumerable<Characteristic> Characteristics { get; set; }
        public IEnumerable<Platform> Platforms { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

WebUI/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WebUI.Models
{
    public class LoginViewModel
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Password { get; set; }
    }
}

WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        // Кол-во товаров
        public int TotalItems { get; set; }

        // Кол-во товаров на одной странице
        public int ItemsPerPage { get; set; }

        // Номер текущей страницы
        public int CurrentPage { get; set; }

        // Общее кол-во страниц
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;
using Domain.Entities;
using Domain.Abstract;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private ICharacteristicRepository repository;

        public CartController(ICharacteristicRepository repo)
        {
            repository = repo;
        }
        public ViewResult Index(Cart cart,string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
  

        public RedirectToRouteResult AddToCart(Cart cart,int CharacteristicId, string returnUrl)
        {
            Characteristic ch = repository.Characteristics.FirstOrDefault
                (b => b.CharacteristicId == CharacteristicId);
            if (ch != null)
            {
                cart.AddItem(ch, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart,int CharacteristicId, string returnUrl)
        {
            Characteristic ch = repository.Characteristics.FirstOrDefault(b => b.CharacteristicId == CharacteristicId);
            if (ch != null)
            {
                cart.RemoveLine(ch);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
    }
}

WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Domain.Concrete;
using Domain.Entities;

namespace WebUI.Controllers
{
    public class HomeController : Controller
    {
        EFDbContext EF = new EFDbContext();

        public ActionResult About()
        {
            return View();

        }
        public ActionResult Index()
        {


            IEnumerable<Characteristic> characteristics = EF.Characteristics;
            IEnumerable<Category> categories = EF.Categories;



            ViewBag.Characteristics = characteristics;
            ViewBag.Categories = categories;


            return View();
        }
        public ActionResult Goods()
        {

            //Извлекаем данные из колекций
            IEnumerable<GamesInOrder> games = EF.GamesInOrders;
            IEnumerable<Characteristic> characteristics = EF.Characteristics;
            IEnumerable<Platform> platforms = EF.Platforms;
            IEnumerable<Purchase> firstPrices = EF.FirstPrices;
            IEnumerable<Category> categories = EF.Categories;

            ViewBag.Games = games;
            ViewBag.Characteristics = characteristics;
            ViewBag.Platforms = platforms;
            ViewBag.FirstPrices = firstPrices;

            ViewBag.Categories = categories;

            return View();
        }
        public ActionResult Orders()
        {
            IEnumerable<Orders> orders = EF.Orders;
            IEnumerable<UserData> userdatas = EF.UserDatas;

            ViewBag.Orders = orders;
            ViewBag.UserDatas = userdatas;

            return View();
        }
        [HttpGet]
        public ActionResult Edit()
        {
    
            return View();
        }
        //    if (game.GameId == 0)
        //        context.Games.Add(game);
        //    else
        //    {
        //        Game dbEntry = context.Games.Find(game.GameId);
        //        if (dbEntry != null)
        //        {
        //            dbEntry.Category = game.Category;
        //            dbEntry.Name = game.Name;
        //            dbEntry.Description = game.Description;
        //            dbEntry.Year = game.Year;
        //            dbEntry.Platform = game.Platform;
        //            dbEntry.Price = game.Price;
        //            dbEntry.Count = game.Count;
        //            dbEntry.ImageData = game.ImageData;
        //            dbEntry.ImageMimeType = game.ImageMimeType;
   
        [HttpPost]
       
        public string Edit(GamesInOrder gio, Characteristic ch, Platform pl, Category c,Purchase p)
        {
           
            Characteristic newCh = new Characteristic();
            Purchase newP = new Purchase();
            
                newCh.Name = ch.Name;
            newCh.SellingPrice = ch.SellingPrice;
            newCh.Year = ch.Year;
            newCh.Description = ch.Description;
            newCh.CategoryId = 1;
            if (pl.NameOfPlatform=="PC")
            {
                newCh.PlatformId = 1;
            }else if (pl.NameOfPlatform == "PS4")
            {
                newCh.PlatformId = 2;
            }else if (pl.NameOfPlatform == "XBOX ONE")
            {
                newCh.PlatformId = 3;
            }
            if (c.NameOfCategory == "Гонки")
            {
                newCh.PlatformId = 1;
            }
            else if (c.NameOfCategory == "RPG")
            {
                newCh.PlatformId = 2;
            }
            else if (c.NameOfCategory == "MMO")
            {
                newCh.PlatformId = 3;
            }
            else if (c.NameOfCategory == "Шутер")
            {
                newCh.PlatformId = 4;
            }
            else if (c.NameOfCategory == "Стратегия")
            {
                newCh.PlatformId = 5;
            }
            

            newCh.ImageData = ch.ImageData;
            newCh.ImageMimeType = ch.ImageMimeType;
            newP.Price = p.Price;
            newP.Count = p.Count;
            EF.Characteristics.Add(newCh);
            EF.FirstPrices.Add(newP);
            EF.SaveChanges();
            return $"Игра {ch.Name} сохранена";
        }
        [HttpGet]
        public ActionResult Buy()
        {

            return View();
        }
        [HttpPost]//Purchase 
        public string Buy(Orders o, UserData ud,Characteristic ch,GamesInOrder gio)
        {
            UserData newUD = new UserData();
            Orders newO = new Orders();
            GamesInOrder newGIO = new GamesInOrder();
            Purchase ppp = EF.FirstPrices
              .FirstOrDefault(g => g.PurchaseId == ch.CharacteristicId);
            ppp.Count--;
            newGIO.CharacteristicsId = ch.CharacteristicId;
            newGIO.CountOfSoldGames = 1;
            newGIO.PriceOfSoldGame = 200;
            newUD.Addres = ud.Addres;
            newUD.NameOfUser = ud.NameOfUser;
            newO.UDId = newUD.UDId;
            newO.DateOfOrder = DateTime.Now;
            newO.StatusOfOrder =o.StatusOfOrder ;
            EF.GamesInOrders.Add(newGIO);
            EF.UserDatas.Add(newUD);
            EF.Orders.Add(newO);
            EF.SaveChanges();
            return $"Уважаемый, {ud.NameOfUser}, с вами скоро свяжутся";
        }
        
    } 
}

WebUI/Views/Cart/Checkout.cshtml
@model Domain.Entities.ShippingDetails
@{
    ViewBag.Title = "GameStore: форма заказа";
}
<h2>Оформить заказ сейчас</h2>
<p>Пожалуйста введи ваши контактные данные, и мы сразу отправим товар!</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary();
    <h3>Данные</h3>
    <div class="form-group">
        <label>Ваше имя:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>

    <h3>Адрес доставки</h3>
    <div class="form-group">
        <label>Адрес:</label>
        @Html.TextBoxFor(x => x.Line1, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label>Город:</label>
        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    </div>
  

    <h3>Опции</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.Payment)
            Оплатить товар?
        </label>
    </div>

    <input class="btn btn-primary" type="submit" value="Обработать заказ" />
   
}

WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ обработан";
}

<h2>Спасибо за выбор нашего магазина.</h2>
<p> Заказ в кратчайшие сроки будет отправлен в службу доставки.</p>

WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Ваша корзина</title>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
</head>
<body>
    <header>
        <div id="logo">
            <a href="~/Home/Index" title="Перейти на главную"><span>Game</span>shop</a>
        </div>
        <div id="menuHead">
            <a style="width:70px" class="buttonA" href="~/Home/About">
                О нас

            </a>
        </div>
    </header>
    <div id="wrapper">
        <div id="leftCol">
            <h3 style="margin-left:550px">Корзина</h3>
            <br />
            <table>
                <thead>
                    <tr>
                        <th>Количество</th>
                        <th>Наименование</th>
                        <th>Цена</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var line in Model.Cart.Lines)
                    {
                        <tr>
                            <td>@line.Quantity</td>
                            <td>@line.Ch.Name</td>
                            <td>@line.Ch.SellingPrice.ToString("# руб")</td>
                            <td>@((line.Quantity * line.Ch.SellingPrice).ToString("# руб"))</td>
                        </tr>
                    }

                </tbody>
                <tfoot>
                    <tr>
                        <td>Итого:</td>
                        <td>@Model.Cart.ComputeTotalValue().ToString("# руб")</td>
                    </tr>
                </tfoot>
            </table>
            <a style="float:left;margin-top:40px;margin-left:450px;width:150px;height:40px" class="buttonA" href="~/Home/Index">Продолжить покупки</a>
            <a style="float:left;margin-top:40px;width:110px;height:40px; " class="buttonA" href="~/Home/Index">Оплатить покупку</a>
        </div>
    </div>
    <footer></footer>
</body>
</html>

WebUI/Views/Cart/Summary.cshtml
@model Domain.Entities.Cart

<div class="navbar-right">
    @Html.ActionLink("Корзина", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-text navbar-right">
    <b>Ваши избранные :</b>
    @Model.Lines.Sum(x => x.Quantity) 
</div>

WebUI/Views/Home/About.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Cart</title>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
</head>
<body>
    <header>
        <div id="logo">
            <a href="~/Home/Index" title="Перейти на главную"><span>Game</span>shop</a>
        </div>

    </header>
    <div id="wrapper">
        <div id="leftCol">
            <h3>О нас</h3> <br />
            (Возможно)Лучший в мире сайт по продажам видеоигр!
        </div>
    </div>
    <footer>
        <div id="footer" name="Admin">

        </div>
    </footer>
</body>
</html>

WebUI/Views/Home/Buy.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Buy</title>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
</head>
<body>
    <header>
        <div id="logo">
            <a href="~/Home/Index" title="Перейти на главную"><span>Game</span>shop</a>
        </div>
        <div id="menuHead">
            <a class="buttonA" style="width:72px;" href="~/Home/About">
                О нас
            </a>
        </div>
    </header>
    <div>
        <h3 style="margin-left:500px;">Оформление покупки</h3>
        <br />
        <form action="" method="post">
            
            <table>
                <tbody>
                    <tr>
                        <td>Id</td>
                        <td><input type="text" name="CharacteristicId" value="" /></td>
                    </tr>
                    <tr>
                        <td>ФИО</td>
                        <td><input type="text" name="NameOfUser" value="" /></td>
                    </tr>
                    <tr>
                        <td>Адрес</td>
                        <td><input type="text" name="Addres" value="" /></td>
                    </tr>
                    <tr>
                        <td> Вы готовы оплатить покупку?</td>
                        <td><input type="checkbox" name="StatusOfOrder" value="" /></td>
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" value="Оформить покупку" /></td>
                    </tr>
                </tbody>
            </table>

        </form>
    </div>
    <footer>
        <div>
            Все права защищены
        </div>
    </footer>
</body>
</html>

WebUI/Views/Home/Edit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
</head>

<body>
    <header>
        <div id="logo">
            <a href="~/Home/Index" title="Перейти на главную"><span>Game</span>shop</a>
        </div>
        <div id="menuHead">
            <a class="buttonA" style="width:72px;" href="~/Home/About">
                О нас
            </a>
        </div>
    </header>
    <div>
        <form action="" method="post">
            <table>
                <tbody>
                    <tr>
                        <td>Название игры</td>
                        <td><input type="text" name="Name" value="" /></td>
                    </tr>
                    <tr>
                        <td>Категория</td>
                        <td><select style="width:160px" name="categories">
        <option  name="NameOfCategory" value="Гонки">Гонки</option>
        <option  name="NameOfCategory" value="RPG">RPG</option>
        <option name="NameOfCategory" value="Шутер">Шутер</option>
        <option  name="NameOfCategory" value="Стратегия">Стратегия</option>
        <option  name="NameOfCategory" value="MMO">MMo</option>
            </select></td>
                    </tr>
                    <tr>
                        <td>Платформа</td>
                        <td>
                            <select  style="width:160px"name="platforms">
                                <option style="width:100px" name="Platform" value="PC">PC</option>
                                <option style="width:100px" name="Platform" value="PS4">PS4</option>
                                <option style="width:100px" name="Platform" value="XBOX ONE">XBOX ONE</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Год производства</td>
                        <td><input type="text" name="Year" value="" /></td>
                    </tr>
                    <tr>
                        <td>Цена по которой игра куплена</td>
                        <td><input type="text" name="Price" value="" /></td>
                    </tr>
                    <tr>
                        <td>Цена по которой игра продается</td>
                        <td><input type="text" name="SellingPrice" value="" /></td>
                    </tr>
                    <tr>
                        <td>Описание</td>
                        <td><textarea name="Description"></textarea> </td>
                    </tr>
                    <tr>
                        <td>Количество</td>
                        <td><input type="text" name="Count" value="" /></td>
                    </tr>
                    <tr>
                        <td>Выберите изображение</td>
                        <td><input type="file" name="ImageMimeType"></td>
                       
                    </tr>
                    <tr>
                        <td colspan="2"><input class="buttonA" type="submit" value="Продолжить" /></td>
                    </tr>
                </tbody>
            </table>

        </form>
    </div>
    <footer></footer>
</body>
</html>

WebUI/Views/Home/Goods.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Goods</title>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
</head>
<body>
    <header>
        <div id="logo">
            <a href="~/Home/Index" title="Перейти на главную"><span>Game</span>shop</a>
        </div>
        <div id="menuHead">
            <a class="buttonA" style="width:72px;" href="~/Home/About">
                О нас
            </a>
        </div>
    </header>
    <div id="wrapper">
        <div id="leftCol">
            <h3 >Товары</h3>
            <br />

                        <table style="position:absolute;left:0px;width:300px;">
                            <thead>
                                <tr>
                                    <td>Действие</td>
                                    <td>Название</td>
                                    <td>Год издания</td>
                                    <td>Цена</td>
                                    
                                </tr>
                            </thead>
                            <tbody>

                                @{

                                    foreach (var c in ViewBag.Characteristics)
                                    {
                                        <tr>
                                            <td><input class="buttonA" type="submit" name="name" value="Изменить" /></td>
                                            <td>@c.Name</td>
                                            <td>@c.Year</td>
                                            <td>@c.SellingPrice</td>
                                            
                                        </tr>
                                    }

                                }

                            </tbody>
                        </table>
                
                        <table style="position:absolute;right:0px;width:640px;">
                            <thead>
                                <tr>
                                    <td style="height:43px;">Количество</td>

                                </tr>
                            </thead>
                            <tbody>

                                @{

                                    foreach (var c in ViewBag.FirstPrices)
                                    {
                                        <tr>

                                            <td style="height:43px">@c.Count</td>

                                        </tr>
                                    }

                                }

                            </tbody>
                        </table>
                
        </div>
    </div>
    <footer>
        <div id="footer" name="Admin">
            <a href="Edit"><input style="width:200px" class="buttonA" type="button" id="AdminButton" value="Добавление игры" /></a>
        </div>
        <div id="footer" name="Admin">
            <a href="Orders"><input style="width:95px" class="buttonA" type="button" id="AdminButton" value="Заказы" /></a>
        </div>
    </footer>
</body>
</html>

WebUI/Views/Home/Index.cshtml
@model Domain.Entities.Characteristic
@{

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


            <h3 style="margin-left:40px;">Товары</h3>
           
           @{ 
               foreach (var item in ViewBag.Characteristics)
               {
                   
            <div id="card">
                
                <strong> Название: </strong>@item.Name<br/>
                <strong> Описание: </strong>@item.Description <br />
                <strong>Год издания: </strong>   @item.Year <br />
                <strong> Цена: </strong> @item.SellingPrice.ToString("# руб") <br />

                     
                      @using (Html.BeginForm("AddToCart", "Cart"))
                    {
                          @Html.HiddenFor(x=>x.CharacteristicId)
                  @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input style="padding-right:0px ;width:120px; text-align: left; margin:0px 0px 0px 0px;" class="buttonA" type="submit" name="name" value="В корзину" />
                      }
</div> 
               }
          }

WebUI/Views/Home/Orders.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Orders</title>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
</head>
<body>
    <header>
        <div id="logo">
            <a href="~/Home/Index" title="Перейти на главную"><span>Game</span>shop</a>
        </div>
        <div id="menuHead">
            <a class="buttonA" style="width:72px;" href="~/Home/About">
                О нас
            </a>
        </div>
    </header>
    <div id="wrapper">
        <div id="leftCol">
            <h3 style="margin-left:410px">Заказы</h3>
            <br />
            <table style="position:absolute;left:0px;width:200px;">
                <thead>
                    <tr>
                        <td>Id заказа</td>
                        <td>Дата заказа</td>
                        <td>Статус заказа</td>
                    </tr>
                </thead>
                <tbody>
                    @{
                        foreach (var o in ViewBag.Orders)
                        {
                    <tr>
                      
                        <td>@o.OrderId</td>
                        <td>@o.DateOfOrder</td>
                        <td>@o.StatusOfOrder</td>

                    </tr>
                        }

                    }

                </tbody>
            </table>

            <table style="position:absolute;right:0px;width:858px;">
                <thead>
                    <tr>
                        <td style="height:43px;">ФИО покупателя</td>
                        <td style="height:43px;">Адрес</td>

                    </tr>
                </thead>
                <tbody>

                    @{

                        foreach (var u in ViewBag.UserDatas)
                        {
                    <tr>
                        <td >@u.NameOfUser</td>
                        <td >@u.Addres</td>
                    </tr>
                        }

                    }

                </tbody>
            </table>
           
        </div>
    </div>
    <footer>
        <div id="footer">
            Все права защищены
        </div>
    </footer>
</body>
</html>

WebUI/Views/Login.cshtml
@model WebUI.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Вход в систему</h3>
    </div>
    <div class="panel-body">
        <p class="lead">Пожалуйста, войдите в систему, чтобы получить доступ к админ. панели:</p>
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary()
            <div class="form-group">
                <label>Имя пользователя:</label>
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>Пароль:</label>
                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
            </div>
            <input type="submit" value="Войти" class="btn btn-primary" />
        }
    </div>
</div>

WebUI/Views/Shared/CarSummury.cshtml
@model Domain.Entities.Game
<div class="well">
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" width="200" height="100"
                 src="@Url.Action("GetImage", "Game",
                new { Model.GameId })" />
        </div>
    }
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.GameId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Добавить в корзину" />
        </div>
    }
    <span class="lead">
        Год издания:
        @Model.Year<br/>

        Платформа:
        @Model.Platform<br/>

        Описание:
        @Model.Description<br/>
                          <br/>
    </span>
</div>

WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>GameStore</title>
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
</head>
<body>
    <header>
        <div id="logo">
            <a href="~/Home/Index" title="Перейти на главную"><span>Game</span>shop</a>
        </div>
        <div id="menuHead">
            <a class="buttonA" style="width:72px;" href="~/Home/About">
                О нас
            </a>
        </div>
        <div>
            <div id="Cartid">
                <a id="Cart" href="~/Cart/Index">
                    <div class="buttonA" style="width:110px;margin-left:150px;margin-bottom:30%; ">Корзина</div>
                </a>
            </div>
        </div>
    </header>
    <div id="wrapper">
        <div id="leftCol">
            @RenderBody()
        </div>
        <div id="categories">
            <h3 style=" margin-left:60px;">Категории</h3>
     <!--       <a><input class="buttonA" type="button" name="categories" value="Все категории" /></a>-->
            @{
                foreach (var item in ViewBag.Categories)
                {
                    <a><input style="width:200px" class="buttonA" type="button" name="categories" value="@item.NameOfCategory" /></a>
                }
            }
        </div>
    </div>
    <footer>
        <div id="footer" name="Admin">
            <a href="~/Home/Goods"><input style="width:155px;" class="buttonA" type="button" id="AdminButton" value="Админ-панель" /></a>
        </div>
    </footer>
</body>
</html>